print('Hello world')
print('Hello SJTU! Hello IEEE!')
print('Shanghai Jiao Tong University')
print('中华人民共和国')
print('上海交通大学')
print('上海市闵行区东川路800号')
print('苟利国家生死以')
print('1+2+3=6') 

print("Shanghai Jiao Tong University")
print("Hello SJTU! Hello IEEE!")
print("中华人民共和国")
print("上海交通大学")
print("上海市闵行区东川路800号")
print("苟利国家生死以")
print("1+2+3=6")